openquantumhardware/qick

- firmware/README.md
- qick_lib/qick/averager_program.py
- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
The main theme here is adding guardrails to protect against the mistakes I've made when learning how to use the QICK.
* freq2reg_adc() always returns a value that will be double the output of freq2reg() - you no longer need to pass all frequencies through adcfreq(), though still useful if you want to know the exact frequency you're getting
* sanity checks for waveform writes, to reject integer overflows and odd-size transfers
* N_AVG in qick.py did not match the actual buffer size in qick.bit; this causes DMA transfers to be silently truncated, and if an averager loop is too fast you will get zero values in the output. I added a sanity check that will raise an exception if a transfer is truncated, and more importantly the QickSoc configuration is automatically read from qick.hwh (and can …
> sanity checks, less hard-coded configuration

- qick_lib/qick/averager_program.py
- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
- qick_lib/qick/streamer.py
* allocate DMA buffers once at initialization, instead of having to get a new continuous memory block for each transfer
* speed up acquire_decimated by using ndarrays instead of iterating over multiple arrays
* merge in Dave's changes, which allow the QickSoc to be proxied over Pyro4
* DataStreamer class handles starting and controlling a separate process for streaming readout of the average buffer (important for decoupling network latency from the readout loop when proxying) - so far only implemented in AveragerProgram
fix some issues from PR #2, flagged by Dave:
* bug in set_nyquist()
* the new progress bar in acquire_round() is often too much clutter - we have decided that acquire() and acquire_round() should just default to progress=False, and users should be explicit when they want …
> DMA improvements, remote proxying, misc. fixes

- qick_lib/qick/qick.py
The "qick_688128.bit" ZCU216 firmware uses different fabric clocks for the DACs and ADCs, which breaks assumptions that I made when writing prepare_freq2reg(). The fix is to use the PLL refclk instead.
> Fix bug with clock multiplier math

- qick_lib/qick/qick.py
I moved refclk_freq to the QickConfig, but forgot to change set_all_clks() accordingly. Fixed.
> fix bug set_all_clks() in previous PR

- qick_lib/qick/qick_asm.py
I broke print(soc) because that used `isinstance(self, QickConfig)` - fixed with a workaround based on `hasattr`.
> fix bug introduced when I moved the QickConfig

- qick_lib/qick/qick.py
ZCU216 appears to have a problem, where the clocks must be configured before downloading the bitstream. We need the config info in the HWH file before configuring the clocks.
This change does things in (we think) the correct order:
1. load the bitstream and HWH in software
2. configure the clocks
3. download the bitstream to the PL
> set the clocks before downloading the bitstream

- qick_lib/qick/helpers.py
- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
We had been mapping the generator and readout channel numbers based on the indices in the names of the IP blocks - this is not very smart and doesn't work when you start mixing different types of generator IPs.
One of the main functions of this numbering is getting the correct port index on the switches connecting the IPs to the DMA. Those switches provide a natural ordering for the IPs that connect to them, and so we now extract this information from the HWH parser (thanks to Graham Schelle and Shane Fleming of Xilinx for useful discussions on this).
This doesn't change any user-side code yet, but all the extracted information goes into the QickConfig dictionary. Future updates will probably change parts of qick_asm to use that information - at that point I expect there will be some API …
> get channel mapping from HWH parser

- qick_lib/qick/__init__.py
- qick_lib/qick/averager_program.py
- qick_lib/qick/helpers.py
- qick_lib/qick/parser.py
- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
- qick_lib/qick/rfboard.py
- qick_lib/qick/streamer.py
Some major changes to the software interface here, probably not fully complete. This will require changes to existing programs, but it was necessary in order to support the new firmware blocks.
* QickProgram now has `declare_readout()` and `declare_gen()` methods that are meant to make more explicit the process of setting up the generator and readout channels you intend to use in a program.
* Channel numbers strictly follow the indices printed in QickSoc.description() - meaning generator channels are now 0-indexed, not 1-indexed.
* The process for defining and firing a pulse has changed - previously you would call `add_pulse()` to save a waveform, optionally `pulse(play=False)` to write registers, and `pulse(play=True)` to fire the pulse; now writing registers is mandatory and done with …
> Reorganization of program configuration and pulsing code, support for new generator and readout blocks

- qick_lib/qick/helpers.py
- qick_lib/qick/qick.py
The qick-amo firmware has more register slice and clock converter blocks, and they are named differently. Had to make the parser smarter to handle this:
* jump through multiple slices/converters in a row if necessary
* check the block type using the actual IP type, not by string-matching the block name
> parser updates to support qick-amo firmware

- qick_lib/qick/averager_program.py
- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
- qick_lib/qick/streamer.py
Instead of requiring `soc.tproc.start_src()` to be set appropriately before running a program, we now have a start_src parameter for the various acquire/acquire_decimated methods.
This option defaults to "internal" but "external" will configure the tProcessor to expect an external trigger (this will only work with a firmware that has an external trigger input).
> start_src option for specifying internal/external trigger

- qick_demos/00_Send_receive_pulse.ipynb
- qick_demos/01_Phase_coherent_readout.ipynb
- qick_demos/02_Sweeping_variables.ipynb
- qick_lib/qick/averager_program.py
- qick_lib/qick/parser.py
- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
- qick_lib/qick/streamer.py
It turns out that the "autoproxy" trick for exposing class members over Pyro costs ~1 ms per call. So with the exception of get_decimated(), we no longer use autoproxied class members (the relevant methods are wrapped instead, which is ugly but worth it).
Now seeing ~4 ms per AveragerProgram execution when running without Pyro (I think the wrapped methods add some overhead), 7-10 ms when running with Pyro.
> reduce pyro overhead

- qick_lib/qick/qick.py
- qick_lib/qick/streamer.py
My changes to poll_data in #33 and #34 broke the logic that clears the streamer buffer. Now fixed.
> fix streamer reset logic

- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
These changes will only affect people testing the new firmware blocks that are under development.
* The v6 full-speed signal generator is now supported.
* The "int4" (interpolated, non-muxed) generator had problems where arbitrary waveforms would overshoot the max DAC value at their peaks. This is called "interpolation overshoot" and it has been resolved by scaling down (to 90%) the default amplitude for pulses using this DAC.
* The Xilinx driver for the NCO (a k a mixer) does strange things to the frequency you give it, which resulted in unexpected output frequencies when the mixer frequency was outside the 1st Nyquist zone. We are now undoing what the driver does, and it now seems OK to use NCO frequencies in the 2nd and 3rd Nyquist zones.
> support for updates to new FW blocks; correct handling of NCO in higher nyquist zones

- README.md
- pyro4/nameserver.sh
- pyro4/server.py
- qick_demos/06_qubit_demos.ipynb
- qick_lib/qick/qick_asm.py
It's now possible to write a partial ("default") set of pulse parameters to a signal generator using `default_pulse_registers()`.
If you are playing multiple pulses on this generator, and the pulses share some params (e.g. freq, phase) but not others, the later `set_pulse_registers()` calls are simplified (and consume less tProc time).
There are also some convenience tweaks to the `pulse()` and `measure()` methods - both now accept lists of DAC channels to pulse simultaneously, and both now have `setup_and_` equivalents that wrap `set_pulse_registers()` (but only accept single DAC channels).
These changes should be fully backwards-compatible.
> restructure pulse setup code

- qick_lib/qick/qick.py
- setup.py
* make the RF board work on pynq 2.6 as well as pynq 2.7
* setup.py now requires pynq>.2.6 (this is a trivial requirement, nobody is running anything older, but it's good to make it explicit)
> misc. version support tweaks

- qick_demos/00_Send_receive_pulse.ipynb
- qick_lib/qick/averager_program.py
- qick_lib/qick/qick_asm.py
- qick_lib/qick/rfboard.py
The RF board schematic in this repo was the production version, while the library supports (in rfboard.py) the preproduction version.
Both schematics are now provided - V1 is preproduction, V2 is production.
> update RF board schematics

- qick_lib/qick/qick.py
* The mixer frequency was often not getting set to exactly the right value (it was often off by fs/2^48). This was a bug in some code that was meant to undo the weird rounding that the RFdc driver does to the frequency you request.
* There was some bad math in the error message that tells you when you've requested incompatible frequencies from the muxed readout.
> fixes to mixer freq rounding and mux readout error message

- qick_lib/qick/averager_program.py
- qick_lib/qick/qick.py
Tested generation of pulse sequences and ADC readout with acquired_decimated() using AveragerProgram. acquire() and other readout functions may still not work.
> Add compatibility with RPyC (https://rpyc.readthedocs.io/).

- qick_lib/qick/ipq_pynq_utils/LICENSE
- qick_lib/qick/ipq_pynq_utils/README.md
- qick_lib/qick/ipq_pynq_utils/clock_models.py
- qick_lib/qick/ipq_pynq_utils/lmx2594_regmap.json
- qick_lib/qick/qick.py
- qick_lib/qick/rfboard.py
* KIT-IPQ has developed a pretty sophisticated library for managing the register map of the LO chip we use on the V2 RF board. We are copying it (with license+attribution), with changes.
* Channels initialize to power-down state, and are enabled at configuration.
* The V1 RF board code has also been changed, since various common code has been tweaked. It should work identically, but that hasn't really been tested.
* Minor breaking change: rfb_set_genrf() is renamed to rfb_set_gen_rf(), rfb_set_ro() is renamed to rfb_set_ro_rf() - for consistency.
> updates for V2 RF board support

- qick_lib/qick/rfboard.py
#69 had a bug, where the IF2RF_PD switches (DAC power-down) were not being switched on and off for RF board V2 (where the switches exist), and were being switched for RF board V! (where they don't). This was mostly harmless for V2, but resulted in errors for V1. Fixed.
> fix bug in RF board PD switches

- qick_lib/qick/qick_asm.py
In #87 I redefined ch_page() and sreg() to use a tProc output number as input, instead of generator channel number, but forgot that those numbers are not always the same (the standard ZCU216 firmware puts the digital output on tProc output 0, so there is an offset of 1). This broke working RAveragerPrograms on those firmwares.
This reverts ch_page() and sreg() to their previous definitions (generator channel number as input), and adds ch_page_ro() and sreg_ro() for tProc-controlled readout.
> fix bug in #87 which broke RAveragerProgram on some firmwares

- firmware/bd/bd_111_2020-2.tcl
- firmware/ip/axis_cdcsync_v1/component.xml
- firmware/ip/axis_cdcsync_v1/src/axis_cdcsync_v1.sv
- firmware/ip/axis_cdcsync_v1/src/cdcsync.sv
- firmware/ip/axis_cdcsync_v1/src/fifo/bin2gray.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/bram_dp.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/bram_simple_dp.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/fifo.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/fifo_axi.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/fifo_dc.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/fifo_dc_axi.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/gray2bin.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/rd2axi.vhd
- firmware/ip/axis_cdcsync_v1/src/fifo/synchronizer_vect.vhd
- firmware/ip/axis_cdcsync_v1/src/tb.sv
- firmware/ip/axis_cdcsync_v1/xgui/axis_cdcsync_v1_v1_0.tcl
Add a new IP block (by Leo) that is used to keep pulse commands in sync between multiple DACs on the same tile. This is included in the build script for the standard ZCU111 firmware, but not yet the other build scripts or the bitstreams.
> add firmware IP for synced clock domain crossing

- qick_lib/qick/qick.py
- qick_lib/qick/rfboard.py
With the parameter external_reference = True when initializing the QickSoC class the INPUT_REF_CLK J11 port on the ZCU216 board will be used. The external reference clock needs to be 10 MHz. To change it after initialization the parameter force_init_clks = True is required.
> Reference clock

- qick_lib/qick/qick.py
- qick_lib/qick/rfboard.py
When reloading the QickSoC with an external_clk=False the setting did not change because the if condition was not fulfilled. Now it checks whether the clocks have previously been set to an external_clk or not.
> bug fix from external_clk = True to external_clk = False

- qick_lib/qick/helpers.py
- qick_lib/qick/qick_asm.py
The recent new firmware supports resetting phases of multiple generator (and tproc-controlled readout) channels at the same time, and ensures stable relative phase between channels after each simultaneous reset. However, if two channels are reset at different tproc times, the relative phase between them is not guaranteed to be a constant from run to run (since the tproc and the DACs uses different clocks). 
So currently the good way to use this phase reset feature is to reset all the generator (and tproc-controlled readout) phases at the beginning of each experiment sequence (at the exact same time), and never reset it again until the end of the sequence.
To do this, this `reset_phase()` function could be handy.
> added a reset_phase function to QickProgram

- qick_lib/qick/helpers.py
- qick_lib/qick/qick.py
PYNQ 3.0 introduced a new interface (https://github.com/Xilinx/PYNQ-Metadata) for getting firmware parameters out of the HWH file. This is much nicer than the old interface, but breaks many of the hacks we had devised for the old interface. As of this PR, there is now a common wrapper that works with both the old and new interfaces.
I haven't done much testing, but this appears to be the case:
* QICK firmware compiled with Vivado 2020.2 (the PYNQ 2.7 version, which we have been using for all firmware) will work on PYNQ 2.6-3.0.
* QICK firmware compiled with Vivado 2022.1 (the PYNQ 3.0 version) works on PYNQ 2.7 and 3.0. I haven't tried on 2.6 but it is probably OK.
> PYNQ 3.0 is now supported

- setup.py
The package is a pure Python one, without any special asset. So it does not actually have a build process, other than collecting files in a tarball/zip archive.
In particular, a wheel is just a special kind of zip archive, containing some metadata, and, for pure Python ones, just the source in certain locations.
For this reason, the wheel construction process seems to depend only on `setuptools` and `wheel`.
Source distributions only require making a tarball, by definition[*].
However, the `cffi` requirement breaks the installation from Git on MacOS, for a reason that is still obscure to me.
https://github.com/qiboteam/qibolab/pull/321#discussion_r1144477425
Since they are not used, and potentially harmful, I just propose to drop `setup_requires` dependencies.
Runtime dependencies are …
> Drop setup requirements

- qick_lib/qick/drivers/readout.py
- qick_lib/qick/qick.py
- qick_lib/qick/qick_asm.py
This adds support for a buffer, similar to the decimated buffer, that writes to the onboard DDR4 memory instead of internal FPGA memory. This buffer can hold a billion IQ samples (a few seconds of data) and can be used in parallel with the regular readout (so you can run a long program with many accumulated shots, but also examine the decimated trace for debugging purposes).
The firmware block itself is still in testing.
> support for DDR4 buffer
